version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_ZSH: "false"
        ENABLE_NONROOT_DOCKER: "false"
        USE_MOBY: "false"
    # user: root
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
      - commandhistory:/commandhistory
      - npm-cache:/root/.npm
      - "~/.ssh:/root/.ssh"
      - "rootnodemodules:/workspace/node_modules"
      - "pluginnodemodules:/workspace/packages/payload-plugin-azure-blob-storage/node_modules"
      - "demonodemodules:/workspace/packages/demo/node_modules"

    # Overrides default command so things don't shut down after the process ends.
    # entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  azure-storage:
    image: mcr.microsoft.com/azure-storage/azurite:3.18.0
    restart: always
    command: "azurite --loose --blobHost 0.0.0.0 --tableHost 0.0.0.0 --queueHost 0.0.0.0"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blobstoragedata:/data"

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    links:
      - mongo

volumes:
  commandhistory:
  npm-cache:
  blobstoragedata:
  mongodata:
  rootnodemodules:
  demonodemodules:
  pluginnodemodules:
